name: Aula de GCS (PUC CAMPINAS)

on: push

defaults:
  run:
    shell: bash
    # working-directory:
    
jobs: 
  primeiro:
    runs-on: ubuntu-latest
    steps:
       - name: Mostrar rodando
         run: echo "teste"
       - name: Mostrar rodando
         run: echo "${{ github.event_name }} foi disparado"
    
  segundo:
     runs-on: windows-latest
     name: Segundo
     steps:
        - name: Criando variaveis de ambiente
          env:
           VAR1: isto é
           VAR2: GitHub Actions
          run: echo $VAR1 $VAR2
      
  Terceiro:
     runs-on: ubuntu-latest
     steps:
       - name: Terceiro
         run: |
           run: echo "${{ github.event_name }} foi disparado"
           echo "No ${{runner.os}}"
